---

- name: Check cassandra dependencies.
  hosts: all
  become: true
  roles:
    - role: deploy-cassandra
      vars:
        keystore_src: "/mnt/stand/cassandraCluster/.certificates"
        truststore_src: "/mnt/stand/cassandraCluster/.certificates"

