---

- name: Ensure shell command is present and up to date
  copy:
    src: "check_cassandra"
    dest: "{{ remote_validation_dir }}/check_cassandra"

- name: Perform tests.
  tags:
    - beta_sh
  command: "cqlsh -f {{ remote_validation_dir }}/check_cassandra"

